########################
# AUTHOR: Reto Schmucki
# DATE: 24 August 2012
# ---------------------
# This code read the result available in the workspace
# generated by the stochastic elasticity analysis and 
# allows to compute the Life-Table Experiment 

library(R.matlab)

setwd("/Users/retoschmucki/Desktop/Dropbox/Reto Schmucki/Stochastic growth rate analysis")

ltre_results <- readMat("LTRE result for LLVR august 2012.mat")
str(ltre_results)
object.size(ltre_results)

ltre_results$muX
attach(ltre_results)

for( k in c(1:2)){

muLogRatiovrH.r = (log(muXvr[,1]) - log(muXrefvr));           # DIFFS ON LOG SCALE
muContribvrH.r = LLVRelastHA * muLogRatiovrH.r;               # USE Hedgerew elasticity REF


}


sigLogRatiovr(:,k) = (log(sigXvr(:,k)) -log(sigXrefvr(:)));         % DIFFS ON LOG SCALE
sigContribvr(:,k) = LLVRelastHFV(:) * sigLogRatiovr(:,k);          %USE REF ELAST

end
